// Generated by gencpp from file robot_sim/GoalSummaryRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_GOALSUMMARYREQUEST_H
#define ROBOT_SIM_MESSAGE_GOALSUMMARYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct GoalSummaryRequest_
{
  typedef GoalSummaryRequest_<ContainerAllocator> Type;

  GoalSummaryRequest_()
    {
    }
  GoalSummaryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoalSummaryRequest_

typedef ::robot_sim::GoalSummaryRequest_<std::allocator<void> > GoalSummaryRequest;

typedef boost::shared_ptr< ::robot_sim::GoalSummaryRequest > GoalSummaryRequestPtr;
typedef boost::shared_ptr< ::robot_sim::GoalSummaryRequest const> GoalSummaryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::GoalSummaryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_sim::GoalSummaryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/GoalSummaryRequest";
  }

  static const char* value(const ::robot_sim::GoalSummaryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_sim::GoalSummaryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalSummaryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::GoalSummaryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_sim::GoalSummaryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_GOALSUMMARYREQUEST_H
