// Generated by gencpp from file robot_sim/GoalSummaryResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_GOALSUMMARYRESPONSE_H
#define ROBOT_SIM_MESSAGE_GOALSUMMARYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct GoalSummaryResponse_
{
  typedef GoalSummaryResponse_<ContainerAllocator> Type;

  GoalSummaryResponse_()
    : goals_reached(0.0)
    , goals_cancelled(0.0)  {
    }
  GoalSummaryResponse_(const ContainerAllocator& _alloc)
    : goals_reached(0.0)
    , goals_cancelled(0.0)  {
  (void)_alloc;
    }



   typedef float _goals_reached_type;
  _goals_reached_type goals_reached;

   typedef float _goals_cancelled_type;
  _goals_cancelled_type goals_cancelled;





  typedef boost::shared_ptr< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalSummaryResponse_

typedef ::robot_sim::GoalSummaryResponse_<std::allocator<void> > GoalSummaryResponse;

typedef boost::shared_ptr< ::robot_sim::GoalSummaryResponse > GoalSummaryResponsePtr;
typedef boost::shared_ptr< ::robot_sim::GoalSummaryResponse const> GoalSummaryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::GoalSummaryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_sim::GoalSummaryResponse_<ContainerAllocator1> & lhs, const ::robot_sim::GoalSummaryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goals_reached == rhs.goals_reached &&
    lhs.goals_cancelled == rhs.goals_cancelled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_sim::GoalSummaryResponse_<ContainerAllocator1> & lhs, const ::robot_sim::GoalSummaryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "416487591520874cc4b095e59568924c";
  }

  static const char* value(const ::robot_sim::GoalSummaryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x416487591520874cULL;
  static const uint64_t static_value2 = 0xc4b095e59568924cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/GoalSummaryResponse";
  }

  static const char* value(const ::robot_sim::GoalSummaryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 goals_reached\n"
"float32 goals_cancelled\n"
;
  }

  static const char* value(const ::robot_sim::GoalSummaryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goals_reached);
      stream.next(m.goals_cancelled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalSummaryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::GoalSummaryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_sim::GoalSummaryResponse_<ContainerAllocator>& v)
  {
    s << indent << "goals_reached: ";
    Printer<float>::stream(s, indent + "  ", v.goals_reached);
    s << indent << "goals_cancelled: ";
    Printer<float>::stream(s, indent + "  ", v.goals_cancelled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_GOALSUMMARYRESPONSE_H
