// Generated by gencpp from file robot_sim/GoalSummary.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_GOALSUMMARY_H
#define ROBOT_SIM_MESSAGE_GOALSUMMARY_H

#include <ros/service_traits.h>


#include <robot_sim/GoalSummaryRequest.h>
#include <robot_sim/GoalSummaryResponse.h>


namespace robot_sim
{

struct GoalSummary
{

typedef GoalSummaryRequest Request;
typedef GoalSummaryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalSummary
} // namespace robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_sim::GoalSummary > {
  static const char* value()
  {
    return "416487591520874cc4b095e59568924c";
  }

  static const char* value(const ::robot_sim::GoalSummary&) { return value(); }
};

template<>
struct DataType< ::robot_sim::GoalSummary > {
  static const char* value()
  {
    return "robot_sim/GoalSummary";
  }

  static const char* value(const ::robot_sim::GoalSummary&) { return value(); }
};


// service_traits::MD5Sum< ::robot_sim::GoalSummaryRequest> should match
// service_traits::MD5Sum< ::robot_sim::GoalSummary >
template<>
struct MD5Sum< ::robot_sim::GoalSummaryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::GoalSummary >::value();
  }
  static const char* value(const ::robot_sim::GoalSummaryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::GoalSummaryRequest> should match
// service_traits::DataType< ::robot_sim::GoalSummary >
template<>
struct DataType< ::robot_sim::GoalSummaryRequest>
{
  static const char* value()
  {
    return DataType< ::robot_sim::GoalSummary >::value();
  }
  static const char* value(const ::robot_sim::GoalSummaryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_sim::GoalSummaryResponse> should match
// service_traits::MD5Sum< ::robot_sim::GoalSummary >
template<>
struct MD5Sum< ::robot_sim::GoalSummaryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::GoalSummary >::value();
  }
  static const char* value(const ::robot_sim::GoalSummaryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::GoalSummaryResponse> should match
// service_traits::DataType< ::robot_sim::GoalSummary >
template<>
struct DataType< ::robot_sim::GoalSummaryResponse>
{
  static const char* value()
  {
    return DataType< ::robot_sim::GoalSummary >::value();
  }
  static const char* value(const ::robot_sim::GoalSummaryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_GOALSUMMARY_H
