// Generated by gencpp from file robot_sim/OdoSensor.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_ODOSENSOR_H
#define ROBOT_SIM_MESSAGE_ODOSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct OdoSensor_
{
  typedef OdoSensor_<ContainerAllocator> Type;

  OdoSensor_()
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_y(0.0)  {
    }
  OdoSensor_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vel_x_type;
  _vel_x_type vel_x;

   typedef float _vel_y_type;
  _vel_y_type vel_y;





  typedef boost::shared_ptr< ::robot_sim::OdoSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::OdoSensor_<ContainerAllocator> const> ConstPtr;

}; // struct OdoSensor_

typedef ::robot_sim::OdoSensor_<std::allocator<void> > OdoSensor;

typedef boost::shared_ptr< ::robot_sim::OdoSensor > OdoSensorPtr;
typedef boost::shared_ptr< ::robot_sim::OdoSensor const> OdoSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::OdoSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::OdoSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_sim::OdoSensor_<ContainerAllocator1> & lhs, const ::robot_sim::OdoSensor_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vel_x == rhs.vel_x &&
    lhs.vel_y == rhs.vel_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_sim::OdoSensor_<ContainerAllocator1> & lhs, const ::robot_sim::OdoSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_sim::OdoSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::OdoSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::OdoSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::OdoSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::OdoSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::OdoSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::OdoSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d133e2df0fdd42b7663a488cd2710f";
  }

  static const char* value(const ::robot_sim::OdoSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d133e2df0fdd42ULL;
  static const uint64_t static_value2 = 0xb7663a488cd2710fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::OdoSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/OdoSensor";
  }

  static const char* value(const ::robot_sim::OdoSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::OdoSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 vel_x\n"
"float32 vel_y\n"
;
  }

  static const char* value(const ::robot_sim::OdoSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::OdoSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vel_x);
      stream.next(m.vel_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdoSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::OdoSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_sim::OdoSensor_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.vel_x);
    s << indent << "vel_y: ";
    Printer<float>::stream(s, indent + "  ", v.vel_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_ODOSENSOR_H
