(cl:defpackage robot_sim-msg
  (:use )
  (:export
   "<KINEMATICDATA>"
   "KINEMATICDATA"
   "<ODOSENSOR>"
   "ODOSENSOR"
   "<PLANNINGACTION>"
   "PLANNINGACTION"
   "<PLANNINGACTIONFEEDBACK>"
   "PLANNINGACTIONFEEDBACK"
   "<PLANNINGACTIONGOAL>"
   "PLANNINGACTIONGOAL"
   "<PLANNINGACTIONRESULT>"
   "PLANNINGACTIONRESULT"
   "<PLANNINGFEEDBACK>"
   "PLANNINGFEEDBACK"
   "<PLANNINGGOAL>"
   "PLANNINGGOAL"
   "<PLANNINGRESULT>"
   "PLANNINGRESULT"
  ))

